use std::{ffi, iter};

use clap::Parser;
use fedimint_core::Amount;
use fedimint_escrow_common::endpoints::EscrowInfo;
use fedimint_escrow_common::oracle::{Beneficiary, OracleAttestationContent, SignedAttestation};
use fedimint_escrow_common::TimeoutAction;
use secp256k1::PublicKey;
use secp256k1::schnorr::Signature;
use serde::Serialize;
use serde_json::json;

use super::EscrowClientModule;
use crate::api::EscrowFederationApi;

#[derive(Parser, Serialize)]
enum Command {
    Create {
        seller_pubkey: PublicKey,
        /// First registered oracle pubkey (Nostr arbitrator 1)
        oracle_pubkey1: PublicKey,
        /// Second registered oracle pubkey (Nostr arbitrator 2)
        oracle_pubkey2: PublicKey,
        /// Third registered oracle pubkey (Nostr arbitrator 3)
        oracle_pubkey3: PublicKey,
        cost: Amount,
        /// Bitcoin block height after which the timeout escape is available
        timeout_block: u32,
        /// Who gets funds on timeout: "release" (seller) or "refund" (buyer)
        #[arg(default_value = "refund")]
        timeout_action: String,
        /// SHA-256 hash of the buyer's secret code (hex). Generated by the buyer's
        /// browser — the service never sees the plaintext.
        #[arg(long)]
        secret_code_hash: String,
        /// Override buyer pubkey (user's ephemeral key). Default: service's own key.
        #[arg(long)]
        buyer_pubkey: Option<PublicKey>,
    },
    Info {
        escrow_id: String,
    },
    Claim {
        escrow_id: String,
        secret_code: String,
    },
    Dispute {
        escrow_id: String,
    },
    /// Resolve a disputed escrow via 2-of-3 oracle attestations.
    /// Pass attestations as a JSON array of SignedAttestation objects.
    ResolveOracle {
        escrow_id: String,
        /// JSON array of SignedAttestation objects (from oracle_sign.py)
        attestations_json: String,
    },
    /// Claim an escrow after the timelock has expired.
    ClaimTimeout {
        escrow_id: String,
    },
    /// Claim an escrow cooperatively (secret_code) and immediately pay the recipient via LN.
    /// This eliminates the custodial window: escrow → wallet → LN happens atomically in one command.
    ClaimAndPay {
        escrow_id: String,
        secret_code: String,
        bolt11: String,
    },
    /// Claim an escrow after timeout and immediately pay the recipient via LN.
    ClaimTimeoutAndPay {
        escrow_id: String,
        bolt11: String,
    },
    /// Create a LN receive invoice. When paid, call await-receive-into-escrow to atomically
    /// lock funds into a Fedimint escrow (eliminates Window ①).
    ReceiveIntoEscrow {
        seller_pubkey: PublicKey,
        oracle_pubkey1: PublicKey,
        oracle_pubkey2: PublicKey,
        oracle_pubkey3: PublicKey,
        cost: Amount,
        timeout_block: u32,
        #[arg(default_value = "refund")]
        timeout_action: String,
        #[arg(long)]
        secret_code_hash: String,
        /// Gateway pubkey to use (skips auto-selection, much faster)
        #[arg(long)]
        gateway_id: Option<PublicKey>,
        /// Override buyer pubkey (user's ephemeral key). Default: service's own key.
        #[arg(long)]
        buyer_pubkey: Option<PublicKey>,
    },
    /// Poll LN receive operation. If buyer paid, atomically creates Fedimint escrow.
    /// Pass all escrow params so no server-side state is needed between calls.
    AwaitReceiveIntoEscrow {
        ln_operation_id: String,
        escrow_id: String,
        seller_pubkey: PublicKey,
        oracle_pubkey1: PublicKey,
        oracle_pubkey2: PublicKey,
        oracle_pubkey3: PublicKey,
        cost: Amount,
        timeout_block: u32,
        #[arg(default_value = "refund")]
        timeout_action: String,
        #[arg(long)]
        secret_code_hash: String,
        /// Poll timeout in seconds (default 5)
        #[arg(long, default_value = "5")]
        timeout: u64,
        /// Override buyer pubkey (user's ephemeral key). Default: service's own key.
        #[arg(long)]
        buyer_pubkey: Option<PublicKey>,
    },
    /// Delegated claim: buyer signed externally, service submits and pays via e-cash → LN.
    ClaimDelegated {
        escrow_id: String,
        secret_code: String,
        /// Hex-encoded Schnorr signature from buyer's ephemeral key over SHA256(secret_code)
        signature_hex: String,
    },
    /// Delegated claim + immediate LN payment.
    ClaimDelegatedAndPay {
        escrow_id: String,
        secret_code: String,
        signature_hex: String,
        bolt11: String,
    },
    /// Delegated timeout claim: authorized party signed externally over SHA256("timeout").
    ClaimTimeoutDelegated {
        escrow_id: String,
        /// Hex-encoded Schnorr signature from authorized party's key
        signature_hex: String,
    },
    /// Delegated timeout claim + immediate LN payment.
    ClaimTimeoutDelegatedAndPay {
        escrow_id: String,
        signature_hex: String,
        bolt11: String,
    },
    /// Delegated dispute: user signed externally over SHA256("dispute").
    DisputeDelegated {
        escrow_id: String,
        /// The disputer's pubkey (must match buyer or seller in escrow)
        disputer_pubkey: PublicKey,
        /// Hex-encoded Schnorr signature from disputer's key
        signature_hex: String,
    },
    PublicKey {},
}

/// Handles the CLI command for the escrow module
pub(crate) async fn handle_cli_command(
    escrow: &EscrowClientModule,
    args: &[ffi::OsString],
) -> anyhow::Result<serde_json::Value> {
    let command =
        Command::parse_from(iter::once(ffi::OsString::from("escrow")).chain(args.iter().cloned()));

    let res = match command {
        Command::Create {
            seller_pubkey,
            oracle_pubkey1,
            oracle_pubkey2,
            oracle_pubkey3,
            cost,
            timeout_block,
            timeout_action,
            secret_code_hash,
            buyer_pubkey,
        } => {
            // escrow_id is still generated server-side (it's just a label, not a secret)
            use random_string::generate;
            let escrow_id: String = generate(
                32,
                "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
            );
            // secret_code_hash is provided by the buyer's browser — service never sees plaintext

            let timeout_action_parsed = match timeout_action.to_lowercase().as_str() {
                "release" => TimeoutAction::Release,
                _ => TimeoutAction::Refund,
            };

            escrow
                .create_escrow(
                    cost,
                    seller_pubkey,
                    vec![oracle_pubkey1, oracle_pubkey2, oracle_pubkey3],
                    escrow_id.clone(),
                    secret_code_hash,
                    timeout_block,
                    timeout_action_parsed,
                    buyer_pubkey,
                )
                .await?;

            Ok(json!({
                "escrow-id": escrow_id,
                "state": "escrow opened!"
            }))
        }
        Command::Info { escrow_id } => {
            let escrow_value: EscrowInfo =
                escrow.module_api.get_escrow_info(escrow_id.clone()).await?;

            Ok(json!({
                "buyer_pubkey": escrow_value.buyer_pubkey,
                "seller_pubkey": escrow_value.seller_pubkey,
                "oracle_pubkeys": [
                    escrow_value.oracle_pubkeys[0],
                    escrow_value.oracle_pubkeys[1],
                    escrow_value.oracle_pubkeys[2],
                ],
                "amount": escrow_value.amount,
                "state": escrow_value.state,
                "timeout_block": escrow_value.timeout_block,
                "timeout_action": escrow_value.timeout_action,
            }))
        }
        Command::Claim {
            escrow_id,
            secret_code,
        } => {
            escrow
                .claim_escrow(escrow_id.clone(), secret_code)
                .await?;

            Ok(json!({
                "escrow_id": escrow_id,
                "status": "resolved"
            }))
        }
        Command::Dispute { escrow_id } => {
            escrow.initiate_dispute(escrow_id.clone()).await?;

            Ok(json!({
                "escrow_id": escrow_id,
                "status": "disputed!"
            }))
        }
        Command::ResolveOracle {
            escrow_id,
            attestations_json,
        } => {
            // Parse attestations from JSON. Each element is:
            // { "pubkey": "<hex>", "signature": "<hex>", "content": { "escrow_id": "...",
            //   "outcome": "buyer"|"seller", "decided_at": <u64>, "reason": "..." } }
            let raw: Vec<serde_json::Value> = serde_json::from_str(&attestations_json)
                .map_err(|e| anyhow::anyhow!("Invalid attestations JSON: {e}"))?;

            let mut attestations: Vec<SignedAttestation> = Vec::with_capacity(raw.len());
            for entry in &raw {
                let pubkey_hex = entry["pubkey"]
                    .as_str()
                    .ok_or_else(|| anyhow::anyhow!("missing pubkey"))?;
                let sig_hex = entry["signature"]
                    .as_str()
                    .ok_or_else(|| anyhow::anyhow!("missing signature"))?;
                let content = &entry["content"];

                let pubkey = pubkey_hex
                    .parse::<PublicKey>()
                    .map_err(|e| anyhow::anyhow!("bad pubkey: {e}"))?;
                let sig_bytes = hex::decode(sig_hex)
                    .map_err(|e| anyhow::anyhow!("bad signature hex: {e}"))?;
                let signature = Signature::from_slice(&sig_bytes)
                    .map_err(|e| anyhow::anyhow!("bad schnorr signature: {e}"))?;

                let outcome_str = content["outcome"]
                    .as_str()
                    .ok_or_else(|| anyhow::anyhow!("missing outcome"))?;
                let outcome = match outcome_str {
                    "buyer" => Beneficiary::Buyer,
                    "seller" => Beneficiary::Seller,
                    other => return Err(anyhow::anyhow!("unknown outcome: {other}")),
                };
                let att_escrow_id = content["escrow_id"]
                    .as_str()
                    .ok_or_else(|| anyhow::anyhow!("missing content.escrow_id"))?
                    .to_string();
                let decided_at = content["decided_at"]
                    .as_u64()
                    .ok_or_else(|| anyhow::anyhow!("missing decided_at"))?;
                let reason = content["reason"].as_str().map(|s| s.to_string());

                attestations.push(SignedAttestation {
                    pubkey,
                    signature,
                    content: OracleAttestationContent {
                        escrow_id: att_escrow_id,
                        outcome,
                        decided_at,
                        reason,
                    },
                });
            }

            escrow
                .resolve_via_oracle(escrow_id.clone(), attestations)
                .await?;

            Ok(json!({
                "escrow_id": escrow_id,
                "status": "resolved via oracle"
            }))
        }
        Command::ClaimTimeout { escrow_id } => {
            escrow.claim_timeout(escrow_id.clone()).await?;

            Ok(json!({
                "escrow_id": escrow_id,
                "status": "timeout claimed"
            }))
        }
        Command::ClaimAndPay {
            escrow_id,
            secret_code,
            bolt11,
        } => {
            escrow.claim_and_pay(escrow_id, secret_code, bolt11).await
        }
        Command::ClaimTimeoutAndPay { escrow_id, bolt11 } => {
            escrow.claim_timeout_and_pay(escrow_id, bolt11).await
        }
        Command::ReceiveIntoEscrow {
            seller_pubkey,
            oracle_pubkey1,
            oracle_pubkey2,
            oracle_pubkey3,
            cost,
            timeout_block,
            timeout_action,
            secret_code_hash,
            gateway_id,
            buyer_pubkey,
        } => {
            let timeout_action_parsed = match timeout_action.to_lowercase().as_str() {
                "release" => TimeoutAction::Release,
                _ => TimeoutAction::Refund,
            };
            escrow
                .receive_into_escrow(
                    cost,
                    seller_pubkey,
                    vec![oracle_pubkey1, oracle_pubkey2, oracle_pubkey3],
                    secret_code_hash,
                    timeout_block,
                    timeout_action_parsed,
                    gateway_id,
                    buyer_pubkey,
                    None,
                )
                .await
        }
        Command::AwaitReceiveIntoEscrow {
            ln_operation_id,
            escrow_id,
            seller_pubkey,
            oracle_pubkey1,
            oracle_pubkey2,
            oracle_pubkey3,
            cost,
            timeout_block,
            timeout_action,
            secret_code_hash,
            timeout,
            buyer_pubkey,
        } => {
            let timeout_action_parsed = match timeout_action.to_lowercase().as_str() {
                "release" => TimeoutAction::Release,
                _ => TimeoutAction::Refund,
            };
            escrow
                .await_receive_into_escrow(
                    ln_operation_id,
                    escrow_id,
                    cost,
                    seller_pubkey,
                    vec![oracle_pubkey1, oracle_pubkey2, oracle_pubkey3],
                    secret_code_hash,
                    timeout_block,
                    timeout_action_parsed,
                    timeout,
                    buyer_pubkey,
                )
                .await
        }
        Command::ClaimDelegated {
            escrow_id,
            secret_code,
            signature_hex,
        } => {
            let sig_bytes = hex::decode(&signature_hex)
                .map_err(|e| anyhow::anyhow!("bad signature hex: {e}"))?;
            let sig = Signature::from_slice(&sig_bytes)
                .map_err(|e| anyhow::anyhow!("bad schnorr signature: {e}"))?;
            escrow
                .claim_escrow_delegated(escrow_id.clone(), secret_code, sig)
                .await?;
            Ok(json!({
                "escrow_id": escrow_id,
                "status": "resolved (delegated)"
            }))
        }
        Command::ClaimDelegatedAndPay {
            escrow_id,
            secret_code,
            signature_hex,
            bolt11,
        } => {
            let sig_bytes = hex::decode(&signature_hex)
                .map_err(|e| anyhow::anyhow!("bad signature hex: {e}"))?;
            let sig = Signature::from_slice(&sig_bytes)
                .map_err(|e| anyhow::anyhow!("bad schnorr signature: {e}"))?;
            escrow
                .claim_delegated_and_pay(escrow_id, secret_code, sig, bolt11)
                .await
        }
        Command::ClaimTimeoutDelegated {
            escrow_id,
            signature_hex,
        } => {
            let sig_bytes = hex::decode(&signature_hex)
                .map_err(|e| anyhow::anyhow!("bad signature hex: {e}"))?;
            let sig = Signature::from_slice(&sig_bytes)
                .map_err(|e| anyhow::anyhow!("bad schnorr signature: {e}"))?;
            escrow
                .claim_timeout_delegated(escrow_id.clone(), sig)
                .await?;
            Ok(json!({
                "escrow_id": escrow_id,
                "status": "timeout claimed (delegated)"
            }))
        }
        Command::ClaimTimeoutDelegatedAndPay {
            escrow_id,
            signature_hex,
            bolt11,
        } => {
            let sig_bytes = hex::decode(&signature_hex)
                .map_err(|e| anyhow::anyhow!("bad signature hex: {e}"))?;
            let sig = Signature::from_slice(&sig_bytes)
                .map_err(|e| anyhow::anyhow!("bad schnorr signature: {e}"))?;
            escrow
                .claim_timeout_delegated_and_pay(escrow_id, sig, bolt11)
                .await
        }
        Command::DisputeDelegated {
            escrow_id,
            disputer_pubkey,
            signature_hex,
        } => {
            let sig_bytes = hex::decode(&signature_hex)
                .map_err(|e| anyhow::anyhow!("bad signature hex: {e}"))?;
            let sig = Signature::from_slice(&sig_bytes)
                .map_err(|e| anyhow::anyhow!("bad schnorr signature: {e}"))?;
            escrow
                .initiate_dispute_delegated(escrow_id.clone(), disputer_pubkey, sig)
                .await?;
            Ok(json!({
                "escrow_id": escrow_id,
                "status": "disputed (delegated)"
            }))
        }
        Command::PublicKey {} => Ok(json!({
            "public_key": escrow.key.public_key().to_string()
        })),
    };

    res
}
